apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o slice1.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: ubuntu-slice1
      name: ubuntu-slice1
    spec:
      ports:
        - name: "5001"
          port: 5001
          targetPort: 5000
      selector:
        io.kompose.service: ubuntu-slice1
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o slice1.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: ubuntu-slice1
      name: ubuntu-slice1
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: ubuntu-slice1
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose.yaml -o slice1.yaml
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.service: ubuntu-slice1
        spec:
          containers:
            - image: jesimielefraimdias/ubuntu-slice1:1.0.0
              name: ubuntu-slice1
              ports:
                - containerPort: 5000
              resources: {}
          restartPolicy: Always
    status: {}
kind: List
metadata: {}

