apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: ubuntu-slice2
  name: ubuntu-slice2
spec:
  containers:
    - args:
        - bash
        - -c
        - source bin/activate && pip3 install wheel && pip3 install -r requirements.txt &&  python3 src/db.py &&  flask run
      env:
        - name: DEBIAN_FRONTEND
          value: noninteractive
        - name: FLASK_APP
          value: src/App.py
        - name: FLASK_RUN_HOST
          value: 0.0.0.0
      image: jesimielefraimdias/ubuntu-slice2:1.0.4
      name: ubuntu-slice2
      ports:
        - containerPort: 5000
      resources: {}
  restartPolicy: OnFailure
status: {}
